version: "3.9"

services:

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: app-mssql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${SA_PASSWORD}
      MSSQL_PID: ${MSSQL_PID}
    ports:
      - "${MSSQL_PORT}:1433"
    volumes:
      - mssql_data:/var/opt/mssql
      - ./db/init.sql:/init.sql:ro
      - ./db/entrypoint.sh:/entrypoint.sh:ro
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    networks:
      - appnet

  backend:
    build: ./backend
    container_name: app-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://db:1433;databaseName=${MSSQL_DB};encrypt=true;trustServerCertificate=true
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: ${SA_PASSWORD}
    ports:
      - "${BACKEND_PORT}:8080"
    depends_on:
      - db
    networks:
      - appnet

  frontend:
    build: ./frontend
    container_name: app-frontend
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - backend
    networks:
      - appnet

  frontend_react:
    build: ./frontendReact
    container_name: app-frontend-react
    ports:
      - "4300:80"
    depends_on:
      - backend
    networks:
      - appnet

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: app-jenkins
    user: root
    ports:
      - "8090:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - appnet

volumes:
  mssql_data:
  jenkins_home:

networks:
  appnet:
    driver: bridge